### ISSUE TITLE
integrate @import watching into browserify/watchify

### ISSUE THREAD

**Issue by jeremydiviney** [cody-greene/scssify#1]
this library seems to work pretty well, however when using watchify.... changes to files being @import..ed into higher level scss files, does not trigger watchify to reload the parent scss file.  This may be complicated, but would be immensely usefull with large project that rely on watchify for build performance

**Comment by chrishoage** [comment]
Are you using webpack from the CLI or using the API though something like gulp? If it's the latter there me be a workaround, but  this is something that out of scope for a browserify transform. One would need a browserify plugin (much like watchify itself) in order to make this work. [Parcelify](https://github.com/rotundasoftware/parcelify) exists, though I have never personally used it, does have  a sass transform and a quick glance though the docs suggests it may follow imports.
