### ISSUE TITLE
Absolute or relative path doesn't work.

### ISSUE THREAD

**Issue by tai2** [cody-greene/scssify#14]
When using scssify, absolute or relative path notation doesn't work. e.g.

```
background: url("/foo.png");
```

At least, Chrome  51.0.2704.84 doesn't resolve this path, though I don't know what the CSS specification says about it.

**Comment by cperryk** [comment]
Couldn't figure out why this is occurring myself, but if you set the transform option `autoInject.styleTag` to `true`, relative paths work as expected.

**Comment by cody-greene** [comment]
Yes this is probably because by default the [`<link>` tag method](https://github.com/cody-greene/scssify/blob/v1.2.0/lib/browser.js#L20) is used, which embeds your css like this:

``` html
<link rel="stylesheet" href="data:text/css;base64,CiAg=">
```

Partial urls in css are supposed to be resolved relative _to the css file_... which in this case doesn't actually exist. It's inlined. Instead of silently failing, you'd think browsers would just resolve relative to the _document_ as is the case with `<style>` tags, but they don't. Unfortunately I can't do anything about this short of base64-encoding all relative images/fonts or adding the full domain, etc – which is beyond of the scope of this module.

Maybe we could submit a ticket to the various browser vendors to handle this? (if one does not already exist)

**Comment by tai2** [comment]
I think setting `autoInject.styleTag` to `true` is enough in general cases.

We can refer this problem in the README with the workaround until browsers handle this case properly, so users don't fall into a trap.

**Comment by cperryk** [comment]
Would it make any sense to make the style tag method the default? What are the advantages of the `<link>` tag method over it?

**Comment by cody-greene** [comment]
I think it makes a lot of sense. The `<link>` embedder function is a little simpler but the base64 encoding increases bundle size and breaks these partial urls. I think I'll just drop this option entirely in a 2.0 release.
