### ISSUE TITLE
I cant seem to get source maps to show up in chrome

### ISSUE THREAD

**Issue by lelandcope** [cody-greene/scssify#15]
Im not sure if I'm doing something wrong but when i debug my css that has been transpiled using scssify I dont get any source maps in chrome. Below is my current config.

```
{
    autoInject: {
        styleTag: true
    },
    sass: {
        sourceMap: true,
        precision: 10
    },
    postcss: {
        autoprefixer: {
            browsers: ['last 2 versions', 'ie 10'],
            cascade: false
        }
    }
}
```

**Comment by cody-greene** [comment]
With `scssify@1.x` can use 

``` javascript
{
  autoInject: {
    styleTag: false
  },
  sass: {
    sourceMapEmbed: true,
    sourceMapContents: true
  }
}
```

But then you'll be dealing with #14. With 2.0 (soon) `<style>` tag sourcemaps will just work. And you can just use:

``` javascript
{
  sass: {
    sourceMapEmbed: true,
    sourceMapContents: true
  }
}
```

Why doesn't this work in 1.x? `<style>` tags need both

``` css
/*# sourceMappingURL=data:application/json;base64,ewoJI== */
/*# sourceURL=src/foo.scss */
```

node-sass doesn't output the second line and since I'm removing the `<link>` tag option in 2.0 I've made sure that scssify adds the `sourceURL` directive.
