### ISSUE TITLE
release on npm and document includePaths

### ISSUE THREAD

**Issue by mkoryak** [cody-greene/scssify#2]
https://github.com/chrishoage/scssify/blob/master/src/index.js#L35

a useful undocumented option here.

would be nice if this was available on npm, cloning the repo to install is not fun. By the way, why cant you PR this into the original?

**Comment by chrishoage** [comment]
I'm not sure what you mean by [not available on npm?](https://www.npmjs.com/package/scssify)

I will update the docs to add includePath. I should probably just link to the sass options page, as that object is just passed to sass directly, so any option you can pass to sass, you can put there. 

As far as "By the way, why cant you PR this into the original.", I am not sure what you are referring to? Are you talking about sassify? If so I wanted to have slightly different approach that the sassify author took (I wanted to use ES6 along with postcss support) and since it was pretty much a rewrite, I couldn't justify doing a PR. 

Hope that answers your questions @mkoryak!

**Comment by mkoryak** [comment]
oh, confused the name of this with sassify. Yes, i see that this is better, will switch to it now :)
