### ISSUE TITLE
Is there any way to use sass with compass

### ISSUE THREAD

**Issue by anianj** [cody-greene/scssify#3]
I just hacked the source to add compass-importer as the sass importer config, do you think this is a proper way to do this, if so, i think we can add a switch in the options to control the use of compass-importer

**Comment by chrishoage** [comment]
Are you referring to: https://www.npmjs.com/package/compass-importer? 

If so, the full sass configuration options are exposed thought he `sass` config option for scssify, so you could set up the options exactly how compass-importer has theirs set up in their readme. 

Does this answer your question @anianj?

**Comment by anianj** [comment]
Thanks @chrishoage but what if i want to set this importer from the package.json, it seems sass only accept this property as a function

**Comment by chrishoage** [comment]
So, looking closer at what compass-importer actually does, it appears it just goes and downloads a packaged version of https://github.com/Igosuki/compass-mixins/

The above link has a package.json, so you could do something like this in your package.json

``` js
{
    "scssify": {
        "sass": {
            "includePaths": ["./node_modules/compass-mixins/lib/"]
        }
    }
}
```

This should work, so long as I am not missing something about what compass-importer actually does. Let me know if that works @anianj

**Comment by anianj** [comment]
Thanks @chrishoage. it works in this way, but the inline-image etc. functions will be unavaliable, may be we need another transform that uses compass to compile the sass.

**Comment by chrishoage** [comment]
I can't see inline-image in compass-mixins or compass-importer. Can you point me to where those mixins live inside either of those projects so I can see what the requirements are? 

Compass does not support libsass (as I am sure you are aware) so a lot of the comass tools that work on the filesystem (spriting) will never work in libsass.

**Comment by anianj** [comment]
It seems it is a buildin function in the compass compile itself.
https://github.com/Compass/compass/blob/stable/core/lib/compass/core/sass_extensions/functions/inline_image.rb
But i have digged into the compass's source and found that compass can not accept a string as a input to compile it into css...so we can not use compass in our transform plugin in a convenient way ...

**Comment by chrishoage** [comment]
Ok, so right now two versions of sass exist. The first is the original old version of sass written in Ruby. This is what Compass is based on. There is a new version of sass, written in C, called [libsass](http://libsass.org/) (and being written in C it is much, much, much faster than the original version). Because Compass is written in Ruby (note the .rb extension on the file you linked) it can not work with libsass. 

Scssify (my project) uses libsass, so scssify will never be able to support compass. The compass-mixins npm module linked above recreates _some_ of the mixins Compass offered, but will never be able to replicate the mixins that worked with the filesystem (as I mentioned in my pervious comment) 

I am going to close this issue now, as Compass is currently unsupported with libsass, and will be for the foreseeable future. 

Please let me know if you run into any more issues using scssify!

**Comment by anianj** [comment]
thanks for you reply
